### ISSUE TITLE
Mining isn't counted with Prohashing

### ISSUE THREAD

**Issue by mrgarbagegamer** [VukkyLtd/SaladBind#89] opened 2021-09-25 19:58 UTC
## Description
For a few people, including me, after an hour or so of mining with Prohashing, earnings stop being counted on Salad. I use T-Rex with Ethash, but I've seen this happen with others, including people using XMRig and RandomX.
## How to reproduce
Mine on Prohashing for over an hour
Watch as earnings stop being counted

**Comment by TheBlueBurger** [comment] 2021-09-25 20:01
I cannot reproduce on etchash. Are you sure this is a saladbind issue and not salad/prohashing?

**Comment by Lyceris-chan** [comment] 2021-09-25 20:02
![image](https://user-images.githubusercontent.com/52329982/134784649-e5ef11f2-a1bc-4406-bcf4-ff07e37a9a5d.png)
this was over night using saladbind 1.5.0 and prohash 

used XMrig on my laptop and desktop (amd ryzen 5 5600x and intel I5 8250U)
used trex ethash on my desktop Nvidia 1070 

seems fine here (europe)

**Comment by mrgarbagegamer** [comment] 2021-09-25 20:57
> I cannot reproduce on etchash. Are you sure this is a saladbind issue and not salad/prohashing?

I'm unsure if this is a Saladbind or Salad issue, but given that I've seen this happen with others with other miners and algorithms, it could be. Also I'm currently using ethash, not etchash, can you try with that and see if the issue occurs with you?

![image](https://user-images.githubusercontent.com/20287746/134785723-65c716f7-618c-47c7-888e-fafa62cd73da.png)


Also, do you have the new more accurate Salad reporting, they're rolling it out slowly and I haven't gotten it yet, there's a chance that this could be a common thread (although mining on Prohashing was giving me earnings earlier).

**Comment by vtheskeleton** [comment] 2021-09-25 22:00
That new more improved Salad reporting **is** Prohashing

**Comment by mrgarbagegamer** [comment] 2021-09-25 22:23
> That new more improved Salad reporting **is** Prohashing

Wouldn't it be that Salad's improved reporting is a feature OF Prohashing, and that it would have to be rolled out to you for you to use Prohashing, because if that's the case, then you should add that text in the setup process so people know.

**Comment by vtheskeleton** [comment] 2021-09-25 23:20
No, the improved updates are because Prohashing pushes updates to Salad quicker. It has nothing to do with the feature being rolled out

**Comment by mrgarbagegamer** [comment] 2021-09-26 00:25
If it's not a Salad related issue, then do you have any other theory as to what's happening here?
![image](https://user-images.githubusercontent.com/20287746/134789081-b82488e1-ae94-416a-a4d9-52efa26f517f.png)
Does the server it is connecting to and everything match yours in terms of formatting? I'm curious why the earnings are not appearing at all on my end.

**Comment by vtheskeleton** [comment] 2021-09-26 00:39
Your password field seems to be empty, which is not supposed to happen

**Comment by vtheskeleton** [comment] 2021-09-28 15:01
> If it's not a Salad related issue, then do you have any other theory as to what's happening here? ![image](https://user-images.githubusercontent.com/20287746/134789081-b82488e1-ae94-416a-a4d9-52efa26f517f.png) Does the server it is connecting to and everything match yours in terms of formatting? I'm curious why the earnings are not appearing at all on my end.
Did you use any advanced arguments when this happened?

**Comment by vtheskeleton** [comment] 2021-09-28 15:04
in specific, did you happen to use the "--pl" argument

**Comment by vtheskeleton** [comment] 2021-09-29 04:56
Anyone with this issue should immediately contact me on discord

**Comment by vtheskeleton** [comment] 2021-09-29 14:04
Problem was discussed on discord. Closing issue as its not caused by Saladbind

**Closed by vtheskeleton** 2021-09-29 14:04 UTC
Labels: bug
