### ISSUE TITLE
T-rex GPU monitoring fails to start

### ISSUE THREAD

**Issue by thepwrtank18** [VukkyLtd/SaladBind#5] opened 2021-07-29 17:25 UTC
![image](https://user-images.githubusercontent.com/57580668/127537263-4322878a-2262-4671-98f5-c76bce697d5c.png)

**Comment by vtheskeleton** [comment] 2021-07-30 08:06
Hello, I have failed to reproduce this issue.
I suggest asking Plerion, since they managed to fix it.
I will close this issue for now

**Comment by vtheskeleton** [comment] 2021-07-30 08:07
Update drivers -Plerion

**Closed by vtheskeleton** 2021-07-30 08:06 UTC
Labels: bug

**Comment by vtheskeleton** [comment] 2021-07-30 08:08
![image](https://user-images.githubusercontent.com/47392011/127622255-27bbf9e4-5d68-4c58-83fa-e7bbb720b64b.png)

**Comment by thepwrtank18** [comment] 2021-07-30 08:11
My drivers are up to date, and this doesn't happen with Cli+.

**Comment by JovannMC** [comment] 2021-07-30 19:05
He meant to downgrade the drivers, not update. Try downgrading your drivers to an older version.

**Comment by Vukkyy** [comment] 2021-07-30 20:59
Unless it's proven that this is a BIND issue, I've tagged this as wontfix for now.
